import Link from "next/link";
import Head from 'next/head'
import { useState } from "react";
import contact from "../pages/contact";
import about from "../pages/about";
import { FaBars, FaTimes} from "react-icons/fa"

export default function Navbar(){
    const [navbar, setNavbar] = useState(false);
    
    return (
        <div>
            <Head>
                <title>Cornelius Owusu-Ansah</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            
        <header className="bg-[#161C2D] border-5 border-white">
                <nav className="px-2 sm:px-4 py-2.5 rounded">
                    <div className="container flex flex-wrap justify-between items-center mx-auto">
                        <Link href="/" className="flex items-center">
                            <span className="self-center text-xl font-semibold text-[#1DB67D] cursor-pointer">Cornelius OA</span>
                        </Link>
                        <button data-collapse-toggle="navbar-default" type="button" id="display-navigation" className="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false"
                        onClick={() => setNavbar(!navbar)}>
                        <span className="sr-only">Open main menu</span>
                        {navbar ? (
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        className="w-6 h-6"
                                        viewBox="0 0 20 20"
                                        fill="currentColor"
                                    >
                                        <path
                                            fillRule="evenodd"
                                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                            clipRule="evenodd"
                                        />
                                    </svg>
                                ) : (
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        className="w-6 h-6"
                                        fill="none"
                                        viewBox="0 0 24 24"
                                        stroke="currentColor"
                                        strokeWidth={2}
                                    >
                                        <path
                                            strokeLinecap="round"
                                            strokeLinejoin="round"
                                            d="M4 6h16M4 12h16M4 18h16"
                                        />
                                    </svg>
                                )}
                        </button>

                        <div className={`w-full md:block md:w-auto ${
                            navbar ? "block" : "hidden"}`} id="display-navigation">
                            <ul className="flex flex-col p-4 mt-4  rounded-lg  md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                <Link href="/about">About</Link>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                    <Link href="/">Portfolio</Link>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                <a href="https://cowans.substack.com/" target='_blank' rel="noreferrer">Blog</a>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                    <Link href="/contact">Contact</Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>  
           
        </div>    
    )
}


         
 


