import Link from "next/link";
import Head from 'next/head'
import { useState } from "react";
// import {BsFillMoonStarsFill} from 'react-icons/bs'
import contact from "../pages/contact";
import about from "../pages/about";

export default function Navbar(){
    // const displayNav = document.getElementById('display-navigation').addEventListener('click', displayNav)
    // const navbar = document.getElementById('display-navigation')

    // function displayNav(){
    //     return navbar.style === 'hidden' ? 
    // }

    return (
        <div>
            <Head>
                <title>Cornelius Owusu-Ansah</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <header className="bg-[#161C2D] border-5 border-white">
                <nav className="px-2 sm:px-4 py-2.5 rounded">
                    <div className="container flex flex-wrap justify-between items-center mx-auto">
                        <Link href="/" className="flex items-center">
                            <span className="self-center text-xl font-semibold text-[#1DB67D]">Cornelius OA</span>
                        </Link>
                        <button data-collapse-toggle="navbar-default" type="button" id="display-navigation" className="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
                        <span className="sr-only">Open main menu</span>
                        <svg className="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                        </button>

                        <div className="hidden w-full md:block md:w-auto" id="display-navigation">
                            <ul className="flex flex-col p-4 mt-4  rounded-lg  md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                <Link href="/about">About</Link>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                    <Link href="/">Portfolio</Link>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                <a href="https://cowans.substack.com/" target='_blank' rel="noreferrer">Blog</a>
                                </li>
                                <li className="text-white hover:bg-gray-300 dark:hover:bg-[#424242] py-0.5 px-2 rounded text-base">
                                    <Link href="/contact">Contact</Link>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        </div>    
    )
}


